# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/internal/common"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/internal/cpudb"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/internal/report"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/internal/script"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/internal/target"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/internal/util"
    schedule:
      interval: "daily"

