name: 🐛 Bug Report/Support
description: Ask a question or report an issue
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a bug report. It helps make PerfSpect better.

        Please try to include as much information as possible.
  - type: textarea
    attributes:
      label: Verbose output from perf-collect
      render: shell
      description: Copy the output of `./perf-collect` with `-v` flag (it will automatically format as a code block)
  - type: textarea
    attributes:
      label: Verbose output from perf-postprocess
      render: shell
      description: Copy the output of `./perf-postprocess` with `-v` flag (it will automatically format as a code block)
  - type: textarea
    attributes:
      label: What steps can reproduce the bug?
      description: Explain the bug, system setup, and provide a code snippet that can reproduce it.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: Is there anything else you think we should know?
