#!/usr/bin/env bash

docker container run                                \
    --volume "$(pwd)"/builder/scripts:/scripts      \
    --volume "$(pwd)":/workdir                      \
    --volume $HOME:$HOME:ro                         \
    --user $(id -u):$(id -g)                        \
    --rm                                            \
    --name build_perfspect                          \
    perfspect_builder:v1                            \
    build
