name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      - name: Cache tool binaries
        id: cache-tools
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: tools-cache
          key: perfspect-tools-binaries-${{ hashFiles('tools/**') }}
      - name: Set cache hit flag
        if: steps.cache-tools.outputs.cache-hit == 'true'
        run: |
          echo "TOOLS_CACHE_HIT=true" >> $GITHUB_ENV
      - name: build perfspect
        run: |
          builder/build.sh
      - name: upload perfspect x86_64
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: perfspect-x86_64
          path: dist/perfspect.tgz
      - name: upload md5 for x86_64
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: md5-x86_64
          path: dist/perfspect.tgz.md5.txt
      - name: upload perfspect aarch64
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: perfspect-aarch64
          path: dist/perfspect-aarch64.tgz
      - name: upload md5 for aarch64
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: md5-aarch64
          path: dist/perfspect-aarch64.tgz.md5.txt
      - name: upload manifest
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: manifest
          path: dist/manifest.json
      - name: upload oss package
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: oss_source
          path: dist/oss_source.tgz
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: download perspect
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: perfspect-x86_64
      - name: run test
        run: |
          tar -xf perfspect.tgz
          cp .github/mock_mlc perfspect/tools/x86_64/
          cd perfspect
          mkdir output
          ./perfspect report --output output
          cp -f perfspect.log output/
      - name: upload report
        if: ${{ always() }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: report-x86_64
          path: perfspect/output/
  test-arm:
    needs: [build]
    runs-on: ubuntu-22.04-arm
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: download perspect aarch64
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: perfspect-aarch64
      - name: run test
        run: |
          tar -xf perfspect-aarch64.tgz
          cd perfspect
          mkdir output
          ./perfspect report --output output
          cp -f perfspect.log output/
      - name: upload report
        if: ${{ always() }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: report-aarch64
          path: perfspect/output/
